In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv(r"D:/MLAI/dataset/Brain Stroke.csv")

In [3]:
data.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [4]:
x=data.iloc[:,[1,2,3,7,8]]
y=data.iloc[:,-1]

In [5]:
# Data Imbalancing(Over Sampling Technique)

In [6]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
ro=RandomOverSampler()
x_resample,y_resample=ro.fit_resample(x,y)
print(Counter(y_resample))

Counter({1: 4733, 0: 4733})


In [7]:
# Feature Scaling by StandardScaler()


In [8]:
# Feature Scaling by StandardScaler()
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_data=ss.fit_transform(x_resample)
x_data

array([[ 0.54148881, -0.46367193,  2.67851427,  1.99742366,  1.13483081],
       [ 1.12483554, -0.46367193,  2.67851427, -0.22786353,  0.49096004],
       [-0.26622204, -0.46367193, -0.3733413 ,  0.95592328,  0.78933918],
       ...,
       [ 0.18250621, -0.46367193, -0.3733413 , -0.13506015,  0.41243922],
       [-0.22134922, -0.46367193, -0.3733413 , -0.29601601,  0.31821423],
       [ 0.58636163, -0.46367193, -0.3733413 ,  1.67786829,  1.55884326]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.2,random_state=21)


In [10]:
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 3802, 1: 3770})
Counter({1: 963, 0: 931})


# Model Imbalancing--> Cross_validation


In [11]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=100,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=5, random_state=100, shuffle=True)


In [12]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression()

In [13]:
#without Iteration based cross validation
scores=cross_val_score(l1,x_train,y_train,cv=kf)
y_pred=cross_val_predict(l1,x_test,y_test,cv=kf)
print(scores)
print(y_pred)

[0.77359736 0.75511551 0.77410832 0.77410832 0.78731836]
[0 0 1 ... 1 1 0]


In [14]:
y_data=y_resample

In [15]:
kx_train_data=[]
kx_test_data=[]
ky_train_data=[]
ky_test_data=[]
for train_data,test_data in kf.split(x_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=kf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=kf)
    kx_train_data.append(x_train)
    kx_test_data.append(x_test)
    ky_train_data.append(y_train)
    ky_test_data.append(y_test)
    print("Checking Balancing y test........",Counter(y_test))
    print(y_pred)
    print(scores)
    print(np.mean(scores)*100)


Checking Balancing y test........ Counter({1: 953, 0: 941})
[1 0 1 ... 0 1 1]
[0.76567657 0.7709571  0.77476882 0.76882431 0.78863937]
77.37732320127654
Checking Balancing y test........ Counter({0: 969, 1: 924})
[1 1 1 ... 1 1 1]
[0.78019802 0.76369637 0.77161716 0.78005284 0.76354029]
77.18209363869015
Checking Balancing y test........ Counter({1: 957, 0: 936})
[1 1 1 ... 1 1 0]
[0.77953795 0.75973597 0.79471947 0.7675033  0.78269485]
77.68383099868771
Checking Balancing y test........ Counter({0: 947, 1: 946})
[1 1 1 ... 1 0 1]
[0.77425743 0.77689769 0.77821782 0.78533686 0.76882431]
77.67068199554433
Checking Balancing y test........ Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.76633663 0.78415842 0.77623762 0.76287979 0.78665786]
77.52540643760545


In [16]:
for train_data,test_data in kf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=kf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=kf)
    print("Checking y_test Balancing:",Counter(y_test))
    print("Checking y_train Balancing:",Counter(y_train))
    print(scores)
    print("-------------------------------------------------------")

Checking y_test Balancing: Counter({1: 953, 0: 941})
Checking y_train Balancing: Counter({0: 3792, 1: 3780})
[0.76567657 0.7709571  0.77476882 0.76882431 0.78863937]
-------------------------------------------------------
Checking y_test Balancing: Counter({0: 969, 1: 924})
Checking y_train Balancing: Counter({1: 3809, 0: 3764})
[0.78019802 0.76369637 0.77161716 0.78005284 0.76354029]
-------------------------------------------------------
Checking y_test Balancing: Counter({1: 957, 0: 936})
Checking y_train Balancing: Counter({0: 3797, 1: 3776})
[0.77953795 0.75973597 0.79471947 0.7675033  0.78269485]
-------------------------------------------------------
Checking y_test Balancing: Counter({0: 947, 1: 946})
Checking y_train Balancing: Counter({1: 3787, 0: 3786})
[0.77425743 0.77689769 0.77821782 0.78533686 0.76882431]
-------------------------------------------------------
Checking y_test Balancing: Counter({1: 953, 0: 940})
Checking y_train Balancing: Counter({0: 3793, 1: 3780})
[0.

# StratifiedKFold Cross Validation

In [17]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,random_state=100,shuffle=True)
skf.get_n_splits(x_data,y_data)
print(skf)

StratifiedKFold(n_splits=5, random_state=100, shuffle=True)


In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression()

In [19]:
scores=cross_val_score(l1,x_train,y_train,cv=skf)
y_pred=cross_val_predict(l1,x_test,y_test,cv=skf)
print(scores)
print(y_pred)

[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
[0 1 1 ... 1 1 0]


In [20]:
kx_train_data=[]
kx_test_data=[]
ky_train_data=[]
ky_test_data=[]
for train_data,test_data in skf.split(x_data,y_data):
    x1_train,x1_test=x_data[train_data],x_data[test_data]
    y1_train,y1_test=y_data[train_data],y_data[test_data] 
    scores=cross_val_score(l1,x_train,y_train,cv=skf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=skf)
    kx_train_data.append(x_train)
    kx_test_data.append(x_test)
    ky_train_data.append(y_train)
    ky_test_data.append(y_test)
    print("Checking Balancing.......:",Counter(y_test))
    print(y_pred)
    print(scores)
    print(np.mean(scores)*100)

    

Checking Balancing.......: Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
77.60479746785775
Checking Balancing.......: Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
77.60479746785775
Checking Balancing.......: Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
77.60479746785775
Checking Balancing.......: Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
77.60479746785775
Checking Balancing.......: Counter({1: 953, 0: 940})
[0 1 1 ... 1 1 0]
[0.78217822 0.76963696 0.7650165  0.77344782 0.78996037]
77.60479746785775


In [21]:
d1=pd.Series.to_frame(pd.Series(kx_test_data))
d2=pd.Series.to_frame(pd.Series(ky_test_data))

In [22]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=skf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=skf)
    print("Checking y_test Balancing:",Counter(y_test))
    print("Checking y_train Balancing: ",Counter(y_train))
    print(scores)
    print("---------------------------------------------------------")

Checking y_test Balancing: Counter({1: 947, 0: 947})
Checking y_train Balancing:  Counter({1: 3786, 0: 3786})
[0.78679868 0.77755776 0.77212682 0.76882431 0.78533686]
---------------------------------------------------------
Checking y_test Balancing: Counter({1: 947, 0: 946})
Checking y_train Balancing:  Counter({0: 3787, 1: 3786})
[0.7960396  0.7669967  0.75841584 0.77410832 0.7681638 ]
---------------------------------------------------------
Checking y_test Balancing: Counter({1: 947, 0: 946})
Checking y_train Balancing:  Counter({0: 3787, 1: 3786})
[0.78745875 0.77821782 0.78283828 0.76486129 0.75561427]
---------------------------------------------------------
Checking y_test Balancing: Counter({0: 947, 1: 946})
Checking y_train Balancing:  Counter({1: 3787, 0: 3786})
[0.76633663 0.76105611 0.78415842 0.77410832 0.79128137]
---------------------------------------------------------
Checking y_test Balancing: Counter({0: 947, 1: 946})
Checking y_train Balancing:  Counter({1: 3787, 

In [23]:
from sklearn.model_selection import ShuffleSplit
sf=ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)
sf.get_n_splits(x_data,y_data)

5

In [24]:
for train_data,test_data in sf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=sf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=skf)
    print("Checking y_test Balancing:",Counter(y_test))
    print("Checking y_train Balancing:",Counter(y_train))
    print(np.mean(scores)*100)
    print(scores)
    print("---------------------------")

Checking y_test Balancing: Counter({1: 950, 0: 944})
Checking y_train Balancing: Counter({0: 3789, 1: 3783})
78.28382838283828
[0.78151815 0.78547855 0.78547855 0.78283828 0.77887789]
---------------------------
Checking y_test Balancing: Counter({0: 954, 1: 940})
Checking y_train Balancing: Counter({1: 3793, 0: 3779})
76.97689768976898
[0.78415842 0.76633663 0.78481848 0.75973597 0.75379538]
---------------------------
Checking y_test Balancing: Counter({0: 962, 1: 932})
Checking y_train Balancing: Counter({1: 3801, 0: 3771})
78.05940594059406
[0.78019802 0.77689769 0.79207921 0.78481848 0.7689769 ]
---------------------------
Checking y_test Balancing: Counter({0: 988, 1: 906})
Checking y_train Balancing: Counter({1: 3827, 0: 3745})
77.72937293729373
[0.78151815 0.76765677 0.77359736 0.77821782 0.78547855]
---------------------------
Checking y_test Balancing: Counter({0: 968, 1: 926})
Checking y_train Balancing: Counter({1: 3807, 0: 3765})
78.006600660066
[0.7709571  0.77623762 0.79

In [25]:
#Logistic Algorithm

In [26]:
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression()
l1.fit(x_train,y_train)


LogisticRegression()

In [27]:
from sklearn.metrics import accuracy_score
y_pred=l1.predict(x_test)
ac=accuracy_score(y_test,y_pred)*100
print(ac)
print("LogisticRegression",y_pred)

75.55438225976768
LogisticRegression [1 0 1 ... 1 1 1]


In [28]:
#KNN Algorithm

In [29]:
from sklearn.neighbors import KNeighborsClassifier
k1=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=1)
k1.fit(x_train,y_train)
yknn_pred=k1.predict(x_test)
print("KNN",yknn_pred)

KNN [1 0 1 ... 0 1 1]


In [30]:
ac_knn=accuracy_score(y_test,yknn_pred)*100
print(ac_knn)

92.76663146779302


In [31]:
#SVM Algorithm

In [32]:
from sklearn.svm import SVC
s1=SVC(random_state=11)
s1.fit(x_train,y_train)

SVC(random_state=11)

In [33]:
ysvm_pred=s1.predict(x_test)
ac_svm=accuracy_score(y_test,ysvm_pred)*100
print(ac_svm)
print("SVM",ysvm_pred)

76.34635691657867
SVM [1 0 1 ... 1 1 1]


In [34]:
#OR

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from collections import Counter
l=LogisticRegression()
k=KNeighborsClassifier()
s=SVC()
r= RandomForestClassifier()

In [36]:
print(l.fit(x_train,y_train))
print(k.fit(x_train,y_train))
print(s.fit(x_train,y_train))
print(r.fit(x_train,y_train))

LogisticRegression()
KNeighborsClassifier()
SVC()
RandomForestClassifier()


In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
for clf in (l,k,s,r):
    y_pred = clf.predict(x_test)
    print(
        clf.__class__.__name__,
        '\n',
        'Accuracy score: ',accuracy_score(y_test, y_pred), '\n',
        'Precision score: ',precision_score(y_test, y_pred, zero_division = 1), '\n',
        'Recall score: ',recall_score(y_test, y_pred, zero_division = 1), '\n',
        'F1 score: ',f1_score(y_test, y_pred, zero_division = 1), '\n',
        'ROC AUC score: ',roc_auc_score(y_test, y_pred), '\n', 

    )

LogisticRegression 
 Accuracy score:  0.7555438225976768 
 Precision score:  0.7190160832544938 
 Recall score:  0.8207343412526998 
 F1 score:  0.7665153807362584 
 ROC AUC score:  0.7569580797172589 

KNeighborsClassifier 
 Accuracy score:  0.9260823653643083 
 Precision score:  0.8686679174484052 
 Recall score:  1.0 
 F1 score:  0.929718875502008 
 ROC AUC score:  0.9276859504132232 

SVC 
 Accuracy score:  0.7634635691657867 
 Precision score:  0.7176684881602914 
 Recall score:  0.8509719222462203 
 F1 score:  0.7786561264822135 
 ROC AUC score:  0.7653619941809614 

RandomForestClassifier 
 Accuracy score:  0.9836325237592397 
 Precision score:  0.96760710553814 
 Recall score:  1.0 
 F1 score:  0.9835369091874667 
 ROC AUC score:  0.983987603305785 



In [38]:
#Voting Classifier

In [45]:
from sklearn.ensemble import VotingClassifier
vote=VotingClassifier(estimators=[("Logistic",l1),("KNN",l1),("SVM",s1),("Random Forest",r)])
vote.fit(x_train,y_train)
y_vote=vote.predict(x_test)
print("Voting Classifier",y_vote)

Voting Classifier [1 0 1 ... 1 1 1]


In [46]:
a_vote=accuracy_score(y_test,y_vote)*100
print("Voting Classifier",a_vote)

Voting Classifier 76.34635691657867


In [47]:
#Bagging Classifier
from sklearn.ensemble import BaggingClassifier
bg=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=14)
bg.fit(x_train,y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5,
                  random_state=14)

In [48]:
bg_vote=bg.predict(x_test)
bg1_vote=accuracy_score(y_test,bg_vote)*100
print(bg1_vote)

97.51847940865892


In [51]:
from sklearn.metrics import accuracy_score
sc1=accuracy_score(y_test,y_pred)*100

In [52]:
print(sc1)

98.36325237592398


In [53]:
y_pred.shape

(1894,)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[937  31]
 [  0 926]]


In [55]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.97      0.98       968
           1       0.97      1.00      0.98       926

    accuracy                           0.98      1894
   macro avg       0.98      0.98      0.98      1894
weighted avg       0.98      0.98      0.98      1894

